[contest]
name = "test"
description = "Test"
token_mode = "infinite"

[[contest.users]]
username = "u1"
password = "p1"

[contest-config]
languages = ["C11 / gcc", "C++17 / g++", "Java / JDK", "Python 3 / CPython"]

[contest-config.mapping]
"C11 / gcc" = [".c"]
"C++17 / g++" = [".cpp", ".cc", ".cxx", ".c++", ".C"]
"Java / JDK" = [".java"]
"Python 3 / CPython" = [".py"]

[task_template]
infile = ""
outfile = ""
task_type = "Batch"
score_mode = "max_subtask" # 2017~
token_mode = "infinite"
score_type = "GroupMin"
score_type_parameters = ""
time_limit = 15
memory_limit = 1024

[[tasks]]
name = "base"
title = "base"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  4 = ["3"]
  5 = ["1", "2", "3", "4"]

[[tasks]]
name = "bicycle"
title = "bicycle"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "card"
title = "card"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]

[[tasks]]
name = "editor"
title = "editor"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "gears"
title = "gears"
time_limit = 0.5
  [tasks.inclusive_tests]
  2 = ["1"]

[[tasks]]
name = "scratchcard"
title = "scratchcard"
time_limit = 3.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]

[[tasks]]
name = "tree"
title = "tree"
time_limit = 1.0
  [tasks.inclusive_tests]
  3 = ["1", "2"]

[[tasks]]
name = "ussr"
title = "ussr"
time_limit = 0.2
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
  4 = ["1", "2", "3"]

[[tasks]]
name = "xmas"
title = "xmas"
time_limit = 1.0
  [tasks.inclusive_tests]
  2 = ["1"]
  3 = ["1", "2"]
